site_name: suda docs v8.0

site_url: 'https://docs.gtd.xyz'

docs_dir: 'sources'

site_dir: 'docs'

nav:
    - 介绍:
        - '欢迎使用': index.md
        - '安装步骤': install.md
        - '更新说明': update.md
    - 配置:
        - '参数设置': 'basic/config.md'
        - '系统变量': 'basic/setting.md'
        - '菜单管理': 'basic/menu.md'
        - '路由机制': 'basic/route.md'
    - 功能:
        - '分类管理': 'basic/taxonomy.md'
        - '标签管理': 'basic/tag.md'
        - '页面管理': 'basic/pages.md'
        - '文章管理': 'basic/articles.md'
        - '应用管理': 'basic/extensions.md'
        - '模板管理': 'basic/theme.md'
        - '上传图片': 'basic/media.md'
        - '用户头像': 'basic/avatar.md'
        - '模态框': 'basic/modalbox.md'
        - '侧边框': 'basic/filterbox.md'
        - '编辑器': 'basic/editor.md'
        - '权限方案': 'basic/policy.md'
        - '内置函数': 'basic/functions.md'
    - 应用:
        - '应用介绍': 'dev-intro.md'
        - '目录信息': 'dev-files.md'
        - '常用命令': 'dev-command.md'
        - '开发应用': 'dev-extension.md'
    - 模板:
        - '制作模板': 'theme.md'
        - '模板插件': 'widget.md'
    - 规范:
        - '图标制作': 'icons.md'

theme:
    name: mkdocs
    custom_dir: mkdocs_gitbook/