name: sync fork
on:
  schedule:
  - cron: "0 2 * * 1-5"
jobs:
  syncfork:
    name: Sync fork
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      run: |
        git checkout main
        git merge upstream/main
